export const RAPlatforms = {
    "1": "Genesis/Mega Drive",
    "2": "Nintendo 64",
    "3": "SNES/Super Famicom",
    "4": "Game Boy",
    "5": "Game Boy Advance",
    "6": "Game Boy Color",
    "7": "NES/Famicom",
    "8": "PC Engine/TurboGrafx-16",
    "9": "Sega CD",
    "10": "32X",
    "11": "Master System",
    "12": "PlayStation",
    "13": "Atari Lynx",
    "14": "Neo Geo Pocket",
    "15": "Game Gear",
    "17": "Atari Jaguar",
    "18": "Nintendo DS",
    "21": "PlayStation 2",
    "23": "Magnavox Odyssey 2",
    "24": "Pokemon Mini",
    "25": "Atari 2600",
    "27": "Arcade",
    "28": "Virtual Boy",
    "29": "MSX",
    "33": "SG-1000",
    "37": "Amstrad CPC",
    "38": "Apple II",
    "39": "Saturn",
    "40": "Dreamcast",
    "41": "PlayStation Portable",
    "43": "3DO Interactive Multiplayer",
    "44": "ColecoVision",
    "45": "Intellivision",
    "46": "Vectrex",
    "47": "PC-8000/8800",
    "49": "PC-FX",
    "51": "Atari 7800",
    "53": "WonderSwan",
    "56": "Neo Geo CD",
    "57": "Fairchild Channel F",
    "63": "Watara Supervision",
    "69": "Mega Duck",
    "71": "Arduboy",
    "72": "WASM-4",
    "73": "Arcadia 2001",
    "74": "Interton VC 4000",
    "75": "Elektor TV Games Computer",
    "76": "PC Engine CD/TurboGrafx-CD",
    "77": "Atari Jaguar CD",
    "78": "Nintendo DSi",
    "80": "Uzebox",
    "101": "Events",
    "102": "Standalone"
}
