{
    "User": "taras240",
    "MemberSince": "2017-06-09 18:29:51",
    "LastActivity": {
        "ID": 0,
        "timestamp": null,
        "lastupdate": null,
        "activitytype": null,
        "User": "taras240",
        "data": null,
        "data2": null
    },
    "RichPresenceMsg": "Testing a Nintendo Entertainment System™: Title Screen",
    "LastGameID": 8617,
    "ContribCount": 0,
    "ContribYield": 0,
    "TotalPoints": 13705,
    "TotalSoftcorePoints": 1451,
    "TotalTruePoints": 32471,
    "Permissions": 1,
    "Untracked": 0,
    "ID": 42956,
    "UserWallActive": 1,
    "Motto": "",
    "Rank": 6717,
    "RecentlyPlayedCount": 0,
    "RecentlyPlayed": [],
    "ULID": "01BJ71X8PCCXRNTP4RSVGFZGHG",
    "UserPic": "/UserPic/taras240.png",
    "TotalRanked": 114555,
    "Awarded": {},
    "RecentAchievements": {},
    "Status": "Offline"
}