[
    {
        "GameID": 1458,
        "ConsoleID": 7,
        "ConsoleName": "NES/Famicom",
        "Title": "Batman: The Video Game",
        "ImageIcon": "/Images/039041.png",
        "ImageTitle": "/Images/035572.png",
        "ImageIngame": "/Images/035573.png",
        "ImageBoxArt": "/Images/011643.png",
        "LastPlayed": "2025-08-09 23:35:17",
        "AchievementsTotal": 41,
        "NumPossibleAchievements": 41,
        "PossibleScore": 437,
        "NumAchieved": 23,
        "ScoreAchieved": 167,
        "NumAchievedHardcore": 22,
        "ScoreAchievedHardcore": 157
    },
    {
        "GameID": 2114,
        "ConsoleID": 7,
        "ConsoleName": "NES/Famicom",
        "Title": "Teenage Mutant Ninja Turtles II: The Arcade Game",
        "ImageIcon": "/Images/076385.png",
        "ImageTitle": "/Images/000747.png",
        "ImageIngame": "/Images/000748.png",
        "ImageBoxArt": "/Images/013120.png",
        "LastPlayed": "2025-07-20 15:24:07",
        "AchievementsTotal": 28,
        "NumPossibleAchievements": 28,
        "PossibleScore": 340,
        "NumAchieved": 17,
        "ScoreAchieved": 170,
        "NumAchievedHardcore": 17,
        "ScoreAchievedHardcore": 170
    },
    {
        "GameID": 629,
        "ConsoleID": 3,
        "ConsoleName": "SNES/Super Famicom",
        "Title": "Mega Man X2",
        "ImageIcon": "/Images/023582.png",
        "ImageTitle": "/Images/035388.png",
        "ImageIngame": "/Images/035380.png",
        "ImageBoxArt": "/Images/000929.png",
        "LastPlayed": "2025-07-17 21:14:10",
        "AchievementsTotal": 70,
        "NumPossibleAchievements": 70,
        "PossibleScore": 667,
        "NumAchieved": 0,
        "ScoreAchieved": 0,
        "NumAchievedHardcore": 0,
        "ScoreAchievedHardcore": 0
    },
    {
        "GameID": 350,
        "ConsoleID": 3,
        "ConsoleName": "SNES/Super Famicom",
        "Title": "Teenage Mutant Ninja Turtles IV: Turtles in Time",
        "ImageIcon": "/Images/044532.png",
        "ImageTitle": "/Images/035357.png",
        "ImageIngame": "/Images/053029.png",
        "ImageBoxArt": "/Images/053030.png",
        "LastPlayed": "2025-07-13 15:18:58",
        "AchievementsTotal": 30,
        "NumPossibleAchievements": 30,
        "PossibleScore": 450,
        "NumAchieved": 19,
        "ScoreAchieved": 175,
        "NumAchievedHardcore": 19,
        "ScoreAchievedHardcore": 175
    },
    {
        "GameID": 323,
        "ConsoleID": 3,
        "ConsoleName": "SNES/Super Famicom",
        "Title": "Final Fight 3",
        "ImageIcon": "/Images/101605.png",
        "ImageTitle": "/Images/036002.png",
        "ImageIngame": "/Images/036004.png",
        "ImageBoxArt": "/Images/006039.png",
        "LastPlayed": "2025-07-12 22:16:32",
        "AchievementsTotal": 59,
        "NumPossibleAchievements": 59,
        "PossibleScore": 740,
        "NumAchieved": 20,
        "ScoreAchieved": 175,
        "NumAchievedHardcore": 20,
        "ScoreAchievedHardcore": 175
    },
    {
        "GameID": 5578,
        "ConsoleID": 21,
        "ConsoleName": "PlayStation 2",
        "Title": "Need for Speed: Carbon - Collectors Edition",
        "ImageIcon": "/Images/108704.png",
        "ImageTitle": "/Images/063888.png",
        "ImageIngame": "/Images/063889.png",
        "ImageBoxArt": "/Images/053404.png",
        "LastPlayed": "2025-07-12 18:01:08",
        "AchievementsTotal": 111,
        "NumPossibleAchievements": 111,
        "PossibleScore": 1065,
        "NumAchieved": 1,
        "ScoreAchieved": 1,
        "NumAchievedHardcore": 1,
        "ScoreAchievedHardcore": 1
    },
    {
        "GameID": 1531,
        "ConsoleID": 7,
        "ConsoleName": "NES/Famicom",
        "Title": "Adventures of Lolo 2",
        "ImageIcon": "/Images/047157.png",
        "ImageTitle": "/Images/007254.png",
        "ImageIngame": "/Images/007256.png",
        "ImageBoxArt": "/Images/011526.png",
        "LastPlayed": "2025-07-01 21:27:40",
        "AchievementsTotal": 34,
        "NumPossibleAchievements": 34,
        "PossibleScore": 465,
        "NumAchieved": 18,
        "ScoreAchieved": 155,
        "NumAchievedHardcore": 18,
        "ScoreAchievedHardcore": 155
    },
    {
        "GameID": 33403,
        "ConsoleID": 1,
        "ConsoleName": "Genesis/Mega Drive",
        "Title": "~Homebrew~ Old Towers",
        "ImageIcon": "/Images/110192.png",
        "ImageTitle": "/Images/110171.png",
        "ImageIngame": "/Images/110172.png",
        "ImageBoxArt": "/Images/110191.png",
        "LastPlayed": "2025-06-23 20:19:39",
        "AchievementsTotal": 16,
        "NumPossibleAchievements": 16,
        "PossibleScore": 125,
        "NumAchieved": 2,
        "ScoreAchieved": 5,
        "NumAchievedHardcore": 2,
        "ScoreAchievedHardcore": 5
    },
    {
        "GameID": 18,
        "ConsoleID": 1,
        "ConsoleName": "Genesis/Mega Drive",
        "Title": "Golden Axe",
        "ImageIcon": "/Images/016753.png",
        "ImageTitle": "/Images/048564.png",
        "ImageIngame": "/Images/048565.png",
        "ImageBoxArt": "/Images/051935.png",
        "LastPlayed": "2025-06-23 20:02:08",
        "AchievementsTotal": 24,
        "NumPossibleAchievements": 24,
        "PossibleScore": 284,
        "NumAchieved": 3,
        "ScoreAchieved": 4,
        "NumAchievedHardcore": 3,
        "ScoreAchievedHardcore": 4
    },
    {
        "GameID": 33774,
        "ConsoleID": 5,
        "ConsoleName": "Game Boy Advance",
        "Title": "~Homebrew~ Luigi MasterMind",
        "ImageIcon": "/Images/113857.png",
        "ImageTitle": "/Images/113853.png",
        "ImageIngame": "/Images/113854.png",
        "ImageBoxArt": "/Images/000002.png",
        "LastPlayed": "2025-06-23 19:43:38",
        "AchievementsTotal": 7,
        "NumPossibleAchievements": 7,
        "PossibleScore": 24,
        "NumAchieved": 7,
        "ScoreAchieved": 24,
        "NumAchievedHardcore": 7,
        "ScoreAchievedHardcore": 24
    }
]