export const GAME_GENRE_CODES = {
    1: "Compilation",
    2: "Strategy",
    3: "Casino",
    4: "Music",
    5: "Action",
    6: "Platformer",
    7: "Puzzle",
    8: "Quiz",
    9: "Shooter",
    10: "Vehicle Simulation",
    11: "Construction and Management Simulation",
    12: "Fighting",
    13: "Sports",
    14: "Role-Playing",
    15: "Racing",
    16: "Beat 'em Up",
    17: "Adventure",
    18: "Education",
    19: "Life Simulation",
    20: "Board Game",
    21: "Stealth",
    22: "Pinball",
    23: "Flight Simulator",
    24: "Visual Novel",
    25: "Horror",
    26: "Sandbox",
    27: "Party",
    28: "MMO"
}