export const RAPlatforms = {
    "1": "Mega Drive",
    "2": "Nintendo 64",
    "3": "SNES",
    "4": "Game Boy",
    "5": "GBA",//"Game Boy Advance",
    "6": "GBC",//"Game Boy Color",
    "7": "NES",
    "8": "PC Engine",
    "9": "Sega CD",
    "10": "32X",
    "11": "Master System",
    "12": "PlayStation",
    "13": "Atari Lynx",
    "14": "Neo Geo Pocket",
    "15": "Game Gear",
    "16": "Game Cube",
    "17": "Atari Jaguar",
    "18": "Nintendo DS",
    "21": "PS2",
    "23": "Magnavox Odyssey 2",
    "24": "Pokemon Mini",
    "25": "Atari 2600",
    "27": "Arcade",
    "28": "Virtual Boy",
    "29": "MSX",
    "33": "SG-1000",
    "37": "Amstrad CPC",
    "38": "Apple II",
    "39": "Saturn",
    "40": "Dreamcast",
    "41": "PSP",
    "43": "3DO",
    "44": "ColecoVision",
    "45": "Intellivision",
    "46": "Vectrex",
    "47": "PC-8000/8800",
    "49": "PC-FX",
    "51": "Atari 7800",
    "53": "WonderSwan",
    "56": "Neo Geo CD",
    "57": "Fairchild Channel F",
    "63": "Watara Supervision",
    "69": "Mega Duck",
    "71": "Arduboy",
    "72": "WASM-4",
    "73": "Arcadia 2001",
    "74": "Interton VC 4000",
    "75": "Elektor TV Games Computer",
    "76": "PC Engine CD/TurboGrafx-CD",
    "77": "Atari Jaguar CD",
    "78": "Nintendo DSi",
    "80": "Uzebox",
    "101": "Events",
    "102": "Standalone"
}
export const PlatformIcons = {
    "1": { "Name": "Genesis/Mega Drive", "IconURL": "https://static.retroachievements.org/assets/images/system/md.png" },
    "2": { "Name": "Nintendo 64", "IconURL": "https://static.retroachievements.org/assets/images/system/n64.png" },
    "3": { "Name": "SNES/Super Famicom", "IconURL": "https://static.retroachievements.org/assets/images/system/snes.png" },
    "4": { "Name": "Game Boy", "IconURL": "https://static.retroachievements.org/assets/images/system/gb.png" },
    "5": { "Name": "Game Boy Advance", "IconURL": "https://static.retroachievements.org/assets/images/system/gba.png" },
    "6": { "Name": "Game Boy Color", "IconURL": "https://static.retroachievements.org/assets/images/system/gbc.png" },
    "7": { "Name": "NES/Famicom", "IconURL": "https://static.retroachievements.org/assets/images/system/nes.png" },
    "8": { "Name": "PC Engine/TurboGrafx-16", "IconURL": "https://static.retroachievements.org/assets/images/system/pce.png" },
    "9": { "Name": "Sega CD", "IconURL": "https://static.retroachievements.org/assets/images/system/scd.png" },
    "10": { "Name": "32X", "IconURL": "https://static.retroachievements.org/assets/images/system/32x.png" },
    "11": { "Name": "Master System", "IconURL": "https://static.retroachievements.org/assets/images/system/sms.png" },
    "12": { "Name": "PlayStation", "IconURL": "https://static.retroachievements.org/assets/images/system/ps1.png" },
    "13": { "Name": "Atari Lynx", "IconURL": "https://static.retroachievements.org/assets/images/system/lynx.png" },
    "14": { "Name": "Neo Geo Pocket", "IconURL": "https://static.retroachievements.org/assets/images/system/ngp.png" },
    "15": { "Name": "Game Gear", "IconURL": "https://static.retroachievements.org/assets/images/system/gg.png" },
    "16": { "Name": "GameCube", "IconURL": "https://static.retroachievements.org/assets/images/system/gc.png" },
    "17": { "Name": "Atari Jaguar", "IconURL": "https://static.retroachievements.org/assets/images/system/jag.png" },
    "18": { "Name": "Nintendo DS", "IconURL": "https://static.retroachievements.org/assets/images/system/ds.png" },
    "19": { "Name": "Wii", "IconURL": "https://static.retroachievements.org/assets/images/system/wii.png" },
    "20": { "Name": "Wii U", "IconURL": "https://static.retroachievements.org/assets/images/system/wiiu.png" },
    "21": { "Name": "PlayStation 2", "IconURL": "https://static.retroachievements.org/assets/images/system/ps2.png" },
    "22": { "Name": "Xbox", "IconURL": "https://static.retroachievements.org/assets/images/system/xbox.png" },
    "23": { "Name": "Magnavox Odyssey 2", "IconURL": "https://static.retroachievements.org/assets/images/system/mo2.png" },
    "24": { "Name": "Pokemon Mini", "IconURL": "https://static.retroachievements.org/assets/images/system/mini.png" },
    "25": { "Name": "Atari 2600", "IconURL": "https://static.retroachievements.org/assets/images/system/2600.png" },
    "26": { "Name": "DOS", "IconURL": "https://static.retroachievements.org/assets/images/system/dos.png" },
    "27": { "Name": "Arcade", "IconURL": "https://static.retroachievements.org/assets/images/system/arc.png" },
    "28": { "Name": "Virtual Boy", "IconURL": "https://static.retroachievements.org/assets/images/system/vb.png" },
    "29": { "Name": "MSX", "IconURL": "https://static.retroachievements.org/assets/images/system/msx.png" },
    "30": { "Name": "Commodore 64", "IconURL": "https://static.retroachievements.org/assets/images/system/c64.png" },
    "31": { "Name": "ZX81", "IconURL": "https://static.retroachievements.org/assets/images/system/zx81.png" },
    "32": { "Name": "Oric", "IconURL": "https://static.retroachievements.org/assets/images/system/oric.png" },
    "33": { "Name": "SG-1000", "IconURL": "https://static.retroachievements.org/assets/images/system/sg1k.png" },
    "34": { "Name": "VIC-20", "IconURL": "https://static.retroachievements.org/assets/images/system/vic-20.png" },
    "35": { "Name": "Amiga", "IconURL": "https://static.retroachievements.org/assets/images/system/amiga.png" },
    "36": { "Name": "Atari ST", "IconURL": "https://static.retroachievements.org/assets/images/system/ast.png" },
    "37": { "Name": "Amstrad CPC", "IconURL": "https://static.retroachievements.org/assets/images/system/cpc.png" },
    "38": { "Name": "Apple II", "IconURL": "https://static.retroachievements.org/assets/images/system/a2.png" },
    "39": { "Name": "Saturn", "IconURL": "https://static.retroachievements.org/assets/images/system/sat.png" },
    "40": { "Name": "Dreamcast", "IconURL": "https://static.retroachievements.org/assets/images/system/dc.png" },
    "41": { "Name": "PlayStation Portable", "IconURL": "https://static.retroachievements.org/assets/images/system/psp.png" },
    "42": { "Name": "Philips CD-i", "IconURL": "https://static.retroachievements.org/assets/images/system/cd-i.png" },
    "43": { "Name": "3DO Interactive Multiplayer", "IconURL": "https://static.retroachievements.org/assets/images/system/3do.png" },
    "44": { "Name": "ColecoVision", "IconURL": "https://static.retroachievements.org/assets/images/system/cv.png" },
    "45": { "Name": "Intellivision", "IconURL": "https://static.retroachievements.org/assets/images/system/intv.png" },
    "46": { "Name": "Vectrex", "IconURL": "https://static.retroachievements.org/assets/images/system/vect.png" },
    "47": { "Name": "PC-8000/8800", "IconURL": "https://static.retroachievements.org/assets/images/system/8088.png" },
    "48": { "Name": "PC-9800", "IconURL": "https://static.retroachievements.org/assets/images/system/9800.png" },
    "49": { "Name": "PC-FX", "IconURL": "https://static.retroachievements.org/assets/images/system/pc-fx.png" },
    "50": { "Name": "Atari 5200", "IconURL": "https://static.retroachievements.org/assets/images/system/5200.png" },
    "51": { "Name": "Atari 7800", "IconURL": "https://static.retroachievements.org/assets/images/system/7800.png" },
    "52": { "Name": "Sharp X68000", "IconURL": "https://static.retroachievements.org/assets/images/system/x68k.png" },
    "53": { "Name": "WonderSwan", "IconURL": "https://static.retroachievements.org/assets/images/system/ws.png" },
    "54": { "Name": "Cassette Vision", "IconURL": "https://static.retroachievements.org/assets/images/system/ecv.png" },
    "55": { "Name": "Super Cassette Vision", "IconURL": "https://static.retroachievements.org/assets/images/system/escv.png" },
    "56": { "Name": "Neo Geo CD", "IconURL": "https://static.retroachievements.org/assets/images/system/ngcd.png" },
    "57": { "Name": "Fairchild Channel F", "IconURL": "https://static.retroachievements.org/assets/images/system/chf.png" },
    "58": { "Name": "FM Towns", "IconURL": "https://static.retroachievements.org/assets/images/system/fm-towns.png" },
    "59": { "Name": "ZX Spectrum", "IconURL": "https://static.retroachievements.org/assets/images/system/zxs.png" },
    "60": { "Name": "Game & Watch", "IconURL": "https://static.retroachievements.org/assets/images/system/g&w.png" },
    "61": { "Name": "Nokia N-Gage", "IconURL": "https://static.retroachievements.org/assets/images/system/n-gage.png" },
    "62": { "Name": "Nintendo 3DS", "IconURL": "https://static.retroachievements.org/assets/images/system/3ds.png" },
    "63": { "Name": "Watara Supervision", "IconURL": "https://static.retroachievements.org/assets/images/system/wsv.png" },
    "64": { "Name": "Sharp X1", "IconURL": "https://static.retroachievements.org/assets/images/system/x1.png" },
    "65": { "Name": "TIC-80", "IconURL": "https://static.retroachievements.org/assets/images/system/tic-80.png" },
    "66": { "Name": "Thomson TO8", "IconURL": "https://static.retroachievements.org/assets/images/system/to8.png" },
    "67": { "Name": "PC-6000", "IconURL": "https://static.retroachievements.org/assets/images/system/pc-6000.png" },
    "68": { "Name": "Sega Pico", "IconURL": "https://static.retroachievements.org/assets/images/system/pico.png" },
    "69": { "Name": "Mega Duck", "IconURL": "https://static.retroachievements.org/assets/images/system/duck.png" },
    "70": { "Name": "Zeebo", "IconURL": "https://static.retroachievements.org/assets/images/system/zeebo.png" },
    "71": { "Name": "Arduboy", "IconURL": "https://static.retroachievements.org/assets/images/system/ard.png" },
    "72": { "Name": "WASM-4", "IconURL": "https://static.retroachievements.org/assets/images/system/wasm4.png" },
    "73": { "Name": "Arcadia 2001", "IconURL": "https://static.retroachievements.org/assets/images/system/a2001.png" },
    "74": { "Name": "Interton VC 4000", "IconURL": "https://static.retroachievements.org/assets/images/system/vc4000.png" },
    "75": { "Name": "Elektor TV Games Computer", "IconURL": "https://static.retroachievements.org/assets/images/system/elek.png" },
    "76": { "Name": "PC Engine CD/TurboGrafx-CD", "IconURL": "https://static.retroachievements.org/assets/images/system/pccd.png" },
    "77": { "Name": "Atari Jaguar CD", "IconURL": "https://static.retroachievements.org/assets/images/system/jcd.png" },
    "78": { "Name": "Nintendo DSi", "IconURL": "https://static.retroachievements.org/assets/images/system/dsi.png" },
    "79": { "Name": "TI-83", "IconURL": "https://static.retroachievements.org/assets/images/system/ti-83.png" },
    "80": { "Name": "Uzebox", "IconURL": "https://static.retroachievements.org/assets/images/system/uze.png" },
    "81": { "Name": "Famicom Disk System", "IconURL": "https://static.retroachievements.org/assets/images/system/fds.png" },
    "100": { "Name": "Hubs", "IconURL": "https://static.retroachievements.org/assets/images/system/hubs.png" },
    "101": { "Name": "Events", "IconURL": "https://static.retroachievements.org/assets/images/system/events.png" },
    "102": { "Name": "Standalone", "IconURL": "https://static.retroachievements.org/assets/images/system/exe.png" }
};
