// export const RAPlatforms = {
//     "1": "Mega Drive",
//     "2": "Nintendo 64",
//     "3": "SNES",
//     "4": "Game Boy",
//     "5": "GBA",//"Game Boy Advance",
//     "6": "GBC",//"Game Boy Color",
//     "7": "NES",
//     "8": "PC Engine",
//     "9": "Sega CD",
//     "10": "32X",
//     "11": "Master System",
//     "12": "PlayStation",
//     "13": "Atari Lynx",
//     "14": "Neo Geo Pocket",
//     "15": "Game Gear",
//     "16": "Game Cube",
//     "17": "Atari Jaguar",
//     "18": "Nintendo DS",
//     "21": "PS2",
//     "23": "Magnavox Odyssey 2",
//     "24": "Pokemon Mini",
//     "25": "Atari 2600",
//     "27": "Arcade",
//     "28": "Virtual Boy",
//     "29": "MSX",
//     "33": "SG-1000",
//     "37": "Amstrad CPC",
//     "38": "Apple II",
//     "39": "Saturn",
//     "40": "Dreamcast",
//     "41": "PSP",
//     "43": "3DO",
//     "44": "ColecoVision",
//     "45": "Intellivision",
//     "46": "Vectrex",
//     "47": "PC-8000/8800",
//     "49": "PC-FX",
//     "51": "Atari 7800",
//     "53": "WonderSwan",
//     "56": "Neo Geo CD",
//     "57": "Fairchild Channel F",
//     "63": "Watara Supervision",
//     "69": "Mega Duck",
//     "71": "Arduboy",
//     "72": "WASM-4",
//     "73": "Arcadia 2001",
//     "74": "Interton VC 4000",
//     "75": "Elektor TV Games Computer",
//     "76": "PC Engine CD/TurboGrafx-CD",
//     "77": "Atari Jaguar CD",
//     "78": "Nintendo DSi",
//     "80": "Uzebox",
//     "101": "Events",
//     "102": "Standalone"
// }
const iconsPrefix = "https://static.retroachievements.org/assets/images/system";
export const RAPlatforms = {
    "1": { "Name": "Mega Drive", "IconURL": `${iconsPrefix}/md.png` },
    "2": { "Name": "Nintendo 64", "IconURL": `${iconsPrefix}/n64.png` },
    "3": { "Name": "SNES", "IconURL": `${iconsPrefix}/snes.png` },
    "4": { "Name": "Game Boy", "IconURL": `${iconsPrefix}/gb.png` },
    "5": { "Name": "Game Boy Advance", "IconURL": `${iconsPrefix}/gba.png` },
    "6": { "Name": "Game Boy Color", "IconURL": `${iconsPrefix}/gbc.png` },
    "7": { "Name": "NES/Famicom", "IconURL": `${iconsPrefix}/nes.png` },
    "8": { "Name": "PC Engine", "IconURL": `${iconsPrefix}/pce.png` },
    "9": { "Name": "Sega CD", "IconURL": `${iconsPrefix}/scd.png` },
    "10": { "Name": "32X", "IconURL": `${iconsPrefix}/32x.png` },
    "11": { "Name": "Master System", "IconURL": `${iconsPrefix}/sms.png` },
    "12": { "Name": "PlayStation", "IconURL": `${iconsPrefix}/ps1.png` },
    "13": { "Name": "Atari Lynx", "IconURL": `${iconsPrefix}/lynx.png` },
    "14": { "Name": "Neo Geo Pocket", "IconURL": `${iconsPrefix}/ngp.png` },
    "15": { "Name": "Game Gear", "IconURL": `${iconsPrefix}/gg.png` },
    "16": { "Name": "GameCube", "IconURL": `${iconsPrefix}/gc.png` },
    "17": { "Name": "Atari Jaguar", "IconURL": `${iconsPrefix}/jag.png` },
    "18": { "Name": "Nintendo DS", "IconURL": `${iconsPrefix}/ds.png` },
    "19": { "Name": "Wii", "IconURL": `${iconsPrefix}/wii.png` },
    "20": { "Name": "Wii U", "IconURL": `${iconsPrefix}/wiiu.png` },
    "21": { "Name": "PlayStation 2", "IconURL": `${iconsPrefix}/ps2.png` },
    "22": { "Name": "Xbox", "IconURL": `${iconsPrefix}/xbox.png` },
    "23": { "Name": "Magnavox Odyssey 2", "IconURL": `${iconsPrefix}/mo2.png` },
    "24": { "Name": "Pokemon Mini", "IconURL": `${iconsPrefix}/mini.png` },
    "25": { "Name": "Atari 2600", "IconURL": `${iconsPrefix}/2600.png` },
    "26": { "Name": "DOS", "IconURL": `${iconsPrefix}/dos.png` },
    "27": { "Name": "Arcade", "IconURL": `${iconsPrefix}/arc.png` },
    "28": { "Name": "Virtual Boy", "IconURL": `${iconsPrefix}/vb.png` },
    "29": { "Name": "MSX", "IconURL": `${iconsPrefix}/msx.png` },
    "30": { "Name": "Commodore 64", "IconURL": `${iconsPrefix}/c64.png` },
    "31": { "Name": "ZX81", "IconURL": `${iconsPrefix}/zx81.png` },
    "32": { "Name": "Oric", "IconURL": `${iconsPrefix}/oric.png` },
    "33": { "Name": "SG-1000", "IconURL": `${iconsPrefix}/sg1k.png` },
    "34": { "Name": "VIC-20", "IconURL": `${iconsPrefix}/vic-20.png` },
    "35": { "Name": "Amiga", "IconURL": `${iconsPrefix}/amiga.png` },
    "36": { "Name": "Atari ST", "IconURL": `${iconsPrefix}/ast.png` },
    "37": { "Name": "Amstrad CPC", "IconURL": `${iconsPrefix}/cpc.png` },
    "38": { "Name": "Apple II", "IconURL": `${iconsPrefix}/a2.png` },
    "39": { "Name": "Saturn", "IconURL": `${iconsPrefix}/sat.png` },
    "40": { "Name": "Dreamcast", "IconURL": `${iconsPrefix}/dc.png` },
    "41": { "Name": "PlayStation Portable", "IconURL": `${iconsPrefix}/psp.png` },
    "42": { "Name": "Philips CD-i", "IconURL": `${iconsPrefix}/cd-i.png` },
    "43": { "Name": "3DO Interactive Multiplayer", "IconURL": `${iconsPrefix}/3do.png` },
    "44": { "Name": "ColecoVision", "IconURL": `${iconsPrefix}/cv.png` },
    "45": { "Name": "Intellivision", "IconURL": `${iconsPrefix}/intv.png` },
    "46": { "Name": "Vectrex", "IconURL": `${iconsPrefix}/vect.png` },
    "47": { "Name": "PC-8000/8800", "IconURL": `${iconsPrefix}/8088.png` },
    "48": { "Name": "PC-9800", "IconURL": `${iconsPrefix}/9800.png` },
    "49": { "Name": "PC-FX", "IconURL": `${iconsPrefix}/pc-fx.png` },
    "50": { "Name": "Atari 5200", "IconURL": `${iconsPrefix}/5200.png` },
    "51": { "Name": "Atari 7800", "IconURL": `${iconsPrefix}/7800.png` },
    "52": { "Name": "Sharp X68000", "IconURL": `${iconsPrefix}/x68k.png` },
    "53": { "Name": "WonderSwan", "IconURL": `${iconsPrefix}/ws.png` },
    "54": { "Name": "Cassette Vision", "IconURL": `${iconsPrefix}/ecv.png` },
    "55": { "Name": "Super Cassette Vision", "IconURL": `${iconsPrefix}/escv.png` },
    "56": { "Name": "Neo Geo CD", "IconURL": `${iconsPrefix}/ngcd.png` },
    "57": { "Name": "Fairchild Channel F", "IconURL": `${iconsPrefix}/chf.png` },
    "58": { "Name": "FM Towns", "IconURL": `${iconsPrefix}/fm-towns.png` },
    "59": { "Name": "ZX Spectrum", "IconURL": `${iconsPrefix}/zxs.png` },
    "60": { "Name": "Game & Watch", "IconURL": `${iconsPrefix}/g&w.png` },
    "61": { "Name": "Nokia N-Gage", "IconURL": `${iconsPrefix}/n-gage.png` },
    "62": { "Name": "Nintendo 3DS", "IconURL": `${iconsPrefix}/3ds.png` },
    "63": { "Name": "Watara Supervision", "IconURL": `${iconsPrefix}/wsv.png` },
    "64": { "Name": "Sharp X1", "IconURL": `${iconsPrefix}/x1.png` },
    "65": { "Name": "TIC-80", "IconURL": `${iconsPrefix}/tic-80.png` },
    "66": { "Name": "Thomson TO8", "IconURL": `${iconsPrefix}/to8.png` },
    "67": { "Name": "PC-6000", "IconURL": `${iconsPrefix}/pc-6000.png` },
    "68": { "Name": "Sega Pico", "IconURL": `${iconsPrefix}/pico.png` },
    "69": { "Name": "Mega Duck", "IconURL": `${iconsPrefix}/duck.png` },
    "70": { "Name": "Zeebo", "IconURL": `${iconsPrefix}/zeebo.png` },
    "71": { "Name": "Arduboy", "IconURL": `${iconsPrefix}/ard.png` },
    "72": { "Name": "WASM-4", "IconURL": `${iconsPrefix}/wasm4.png` },
    "73": { "Name": "Arcadia 2001", "IconURL": `${iconsPrefix}/a2001.png` },
    "74": { "Name": "Interton VC 4000", "IconURL": `${iconsPrefix}/vc4000.png` },
    "75": { "Name": "Elektor TV Games Computer", "IconURL": `${iconsPrefix}/elek.png` },
    "76": { "Name": "PC Engine CD", "IconURL": `${iconsPrefix}/pccd.png` },
    "77": { "Name": "Atari Jaguar CD", "IconURL": `${iconsPrefix}/jcd.png` },
    "78": { "Name": "Nintendo DSi", "IconURL": `${iconsPrefix}/dsi.png` },
    "79": { "Name": "TI-83", "IconURL": `${iconsPrefix}/ti-83.png` },
    "80": { "Name": "Uzebox", "IconURL": `${iconsPrefix}/uze.png` },
    "81": { "Name": "Famicom Disk System", "IconURL": `${iconsPrefix}/fds.png` },
    "100": { "Name": "Hubs", "IconURL": `${iconsPrefix}/hubs.png` },
    "101": { "Name": "Events", "IconURL": `${iconsPrefix}/events.png` },
    "102": { "Name": "Standalone", "IconURL": `${iconsPrefix}/exe.png` }
};
